-- =============================================================
-- TT_550_WIN: 07_menu (메뉴)
-- 고객사:     테스트
-- 생성일시:   2026-05-13 10:38:44
-- 실행 모드:  PYTHON (psycopg2 2.9.12 (dt dec pq3 ext lo64))
-- 원본 DB:   localhost:15432/wms-bnk-local (schema=public, PG 15.17)
-- 대상 테이블: sm_menu
-- 적용 방법: psql -h <host> -U <user> -d <db> -f 07_menu.sql
-- =============================================================
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
BEGIN;

-- FK 역순 DELETE
DELETE FROM "public"."sm_menu";

-- FK 정순 INSERT
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IV3200','재고실사','ZMROOT',3200,'MG','#','P','N','N','N','icon-st.png',0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('STSC01','재고실사일정등록','IV3200',3210,'MN','/be/iv3200/stsc01','P','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('STRG01','실사재고등록','IV3200',3220,'MN','/be/iv3200/strg01','P','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('STCP01','재고실사비교','IV3200',3230,'MN','/be/iv3200/stcp01','P','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('OBRQ01','출하예정','OW5000',5010,'MN','/be/ow5000/obrq01','P','Y','N','Y',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('DLPB01','송장발행','OW5000',5015,'MN','/be/ow5000/dlpb01','P','N','N','Y',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('DLPC01','송장처리','OW5000',5040,'MN','/be/ow5000/dlpc01','P','N','N','Y',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('DLPC02','송장처리(바코드)','OW5000',5041,'MN','/be/ow5000/dlpc02','P','Y','N','Y',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('MD8000','기준정보','ZMROOT',8000,'MG','#','P','N','N','N','icon-mdm.png',0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('MDBZ01','사업장','MD8000',8010,'MN','/be/md8000/mdbz01','P','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('MDWH01','창고','MD8000',8030,'MN','/be/md8000/mdwh01','P','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('MDLC01','위치','MD8000',8040,'MN','/be/md8000/mdlc01','P','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('MDPD01','품목','MD8000',8050,'MN','/be/md8000/mdpd01','P','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('MDCT01','거래처','MD8000',8060,'MN','/be/md8000/mdct01','P','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('MDCP01','업체품목','MD8000',8070,'MN','/be/md8000/mdcp01','P','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('MDST01','세트구성','MD8000',8080,'MN','/be/md8000/mdst01','P','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('MDCR01','차량','MD8000',8090,'MN','/be/md8000/mdcr01','P','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('MDUS01','사용자','MD8000',8100,'MN','/be/md8000/mdus01','P','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('SM9000','시스템설정','ZMROOT',9000,'MG','#','P','N','N','N','icon-system.png',0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('PDST01','품목설정','SM9000',9010,'MN','/be/sm9000/pdst01','P','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('SMMG01','권한그룹','SM9000',9050,'MN','/be/sm9000/smmg01','P','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('MNST01','메뉴별설정','SM9000',9060,'MN','/be/sm9000/mnst01','P','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('SCST01','보안설정','SM9000',9070,'MN','/be/sm9000/scst01','P','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IF9100','I/F관리','ZMROOT',9100,'MG','#','P','N','N','N','icon-ifMng.png',0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IFST01','I/F설정','IF9100',9110,'MN','/be/if9100/ifst01','P','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IFBH01','I/F처리이력','IF9100',9120,'MN','/be/if9100/ifbh01','P','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('DVST01','택배사설정','IF9100',9130,'MN','/be/if9100/dvst01','P','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('SMMN01','메뉴','MM9200',9210,'MN','/be/mm9200/smmn01','P','N','N','N',NULL,0,'Y','Y','N','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('SMCC01','공통코드','MM9200',9220,'MN','/be/mm9200/smcc01','P','N','N','N',NULL,0,'Y','Y','N','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('MDLP01','출력물관리','MM9200',9230,'MN','/be/mm9200/mdlp01','P','N','N','N',NULL,0,'Y','Y','N','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('NOTI01','공지사항','MM9200',9240,'MN','/be/mm9200/noti01','P','N','N','N',NULL,0,'Y','Y','Y','N','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('SCRG01','스케쥴러','MM9200',9250,'MN','/be/mm9200/scrg01','P','N','N','N',NULL,0,'Y','Y','N','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('SCEX01','스케쥴러 실행이력','MM9200',9260,'MN','/be/mm9200/scex01','P','N','N','N',NULL,0,'Y','Y','N','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('SCCH01','스케쥴러 변경이력','MM9200',9270,'MN','/be/mm9200/scch01','P','N','N','N',NULL,0,'Y','Y','N','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('LGCO01','시스템접근로그','SS9300',9310,'MN','/be/ss9300/lgco01','P','N','N','N',NULL,0,'Y','Y','N','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('LGAP01','시스템API로그','SS9300',9320,'MN','/be/ss9300/lgap01','P','N','N','N',NULL,0,'Y','Y','N','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('LGER01','시스템에러로그','SS9300',9330,'MN','/be/ss9300/lger01','P','N','N','N',NULL,0,'Y','Y','N','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('LGMN01','시스템메뉴로그','SS9300',9340,'MN','/be/ss9300/lgmn01','P','N','N','N',NULL,0,'Y','Y','N','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('MM9200','운영관리','ZMROOT',9200,'MG','#','P','N','N','N','icon-sysMng.png',0,'Y','Y','N','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('SS9300','시스템현황','ZMROOT',9300,'MG','#','P','N','N','N','icon-sysCondition.png',0,'Y','Y','N','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('OWPC01','피킹처리','OW5000',5030,'MN','/be/ow5000/owpc01','P','Y','N','Y',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,'hgyu','2026-03-26 11:07:25'::timestamp);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('OWRB01','피킹지시','OW5000',5023,'MN','/be/ow5000/owrb01','P','Y','N','Y',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('OBCX01','출하처리취소','OW5000',5061,'MN','/be/ow5000/obcx01','P','N','N','Y',NULL,0,'Y','Y','Y','N','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IVSTRQ01','세트작업요청','IV3000',3075,'MN','/be/iv3000/ivstrq01','P','N','N','Y',NULL,NULL,'Y','Y','Y','Y','administrator','2026-02-05 12:07:23'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('OW5000','출고관리','ZMROOT',5000,'MG','#','P','N','N','Y','icon-ow.png',0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('LDPC01','검수처리','OW5000',5052,'MN','/be/ow5000/ldpc01','P','N','N','Y',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('BRSC01M','재고조회','IV3100M',13110,'MN','/bm/iv3100m/brsc01m','M','N','N','N','icon-brsc.png',73,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('OBSC01','출하현황','OW5000',5090,'MN','/be/ow5000/obsc01','P','N','N','Y',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,'jhkim816','2026-04-09 10:10:47'::timestamp);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('OWPC01M','피킹','OW5000M',15030,'MN','/bm/ow5000m/owrq01m','M','Y','N','Y','icon-owrq.png',31,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,'jhkim816','2026-04-09 11:52:20'::timestamp);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IVMC01','재고마감','IV3100',3150,'MN','/be/iv3100/ivmc01','P','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('SKHT01','SKU이력조회','IV3100',3160,'MN','/be/iv3100/skht01','P','N','N','Y',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('OBPC01','출하처리','OW5000',5060,'MN','/be/ow5000/obpc01','P','Y','N','Y',NULL,0,'Y','Y','Y','N','administrator','2025-08-28 14:23:33.536000'::timestamp,'jhkim816','2026-04-09 10:08:14'::timestamp);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('OBST01','출하설정','SM9000',9020,'MN','/be/sm9000/obst01','P','N','N','N',NULL,0,'Y','Y','Y','N','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('LPST01','출력물설정','SM9000',9030,'MN','/be/sm9000/lpst01','P','N','N','N',NULL,0,'Y','Y','Y','N','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('ALSH01','알람조회','SM9000',9080,'MN','/be/sm9000/alsh01','P','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IWRQ01','입고예정','IW1000',1010,'MN','/be/iw1000/iwrq01','P','Y','N','Y',NULL,0,'N','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IWSC01','입고현황','IW1000',1030,'MN','/be/iw1000/iwsc01','P','N','N','Y',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('RTRQ01','반품예정','RT2000',2010,'MN','/be/rt2000/rtrq01','P','Y','N','Y',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IV3000','재고관리','ZMROOT',3000,'MG','#','P','N','N','Y','icon-iv.png',0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IVMV01','재고이동','IV3000',3010,'MN','/be/iv3000/ivmv01','P','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IVMVRQ01','재고이동요청','IV3000',3020,'MN','/be/iv3000/ivmvrq01','P','Y','N','Y',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IVIO01','수불조회','IV3100',3140,'MN','/be/iv3100/ivio01','P','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('USCD01','사용자코드','SM9000',9040,'MN','/be/sm9000/uscd01','P','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IW1000M','[입고관리]','ZMROOT',11000,'MG','#','M','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IV3000M','[재고관리]','ZMROOT',13000,'MG','#','M','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IV3100M','[재고조회]','ZMROOT',13100,'MG','#','M','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('OW5000M','[출고관리]','ZMROOT',15000,'MG','#','M','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('RT2000','반품관리','ZMROOT',2000,'MG','#','P','N','N','Y','icon-rt.png',0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('ALST01','알람등록','CM9400',8520,'MN','/be/cm9400/alst01','P','N','N','N',NULL,NULL,'Y','Y','N','N','administrator','2026-01-14 10:20:05'::timestamp,'mjjeon','2026-01-14 10:20:16'::timestamp);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IV3200M','[재고실사]','ZMROOT',13200,'MG','#','M','N','N','N',NULL,999,'Y','Y','Y','N','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IVTC01','상태변경','IV3000',3045,'MN','/be/iv3000/ivtc01','P','N','N','N',NULL,NULL,'Y','Y','Y','Y','administrator','2026-02-05 12:08:44'::timestamp,'bnk','2026-02-05 12:08:53'::timestamp);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IVPD01','재고조회(품목별)','IV3100',3110,'MN','/be/iv3100/ivpd01','P','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IW1000','입고관리','ZMROOT',1000,'MG','#','P','N','N','Y','icon-iw.png',0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IWPC01','입고처리','IW1000',1020,'MN','/be/iw1000/iwpc01','P','Y','N','Y',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('RTPC01','반품처리','RT2000',2020,'MN','/be/rt2000/rtpc01','P','Y','N','Y',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IVAD01','재고조정','IV3000',3030,'MN','/be/iv3000/ivad01','P','N','N','Y',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('LDRQ01','검수지시','OW5000',5050,'MN','/be/ow5000/ldrq01','P','N','N','N',NULL,NULL,'Y','Y','Y','Y','administrator','2026-04-09 10:09:59'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IVSK01','SKU변경','IV3000',3050,'MN','/be/iv3000/ivsk01','P','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IVST01','세트작업','IV3000',3080,'MN','/be/iv3000/ivst01','P','N','N','Y',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IV3100','재고조회','ZMROOT',3100,'MG','#','P','N','N','Y','icon-ivs.png',0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IWRQ01M','입고','IW1000M',11100,'MN','/bm/iw1000m/iwrq01m','M','Y','N','Y','icon-iwrq.png',1,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,'admin','2025-10-28 15:39:46'::timestamp);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('SMBD01','고객문의','SS9300',9360,'MN','/be/ss9300/smbd01','P','N','N','N',NULL,0,'Y','Y','N','N','administrator','2025-08-28 14:23:33.536000'::timestamp,'admin','2025-08-29 09:08:33'::timestamp);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IVAD01M','재고조정','IV3000M',13030,'MN','/bm/iv3000m/ivad01m','M','N','N','N','icon-ivad.png',999,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('OBCR01','배송차량등록','OW5000',5055,'MN','/be/ow5000/obcr01','P','N','N','Y',NULL,NULL,'Y','Y','N','Y','administrator','2026-03-31 12:16:10.329347'::timestamp,'jhkim816','2026-04-09 10:09:01'::timestamp);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('OBRQ01M','출하','OW5000M',15080,'MN','/bm/ow5000m/obrq01m','M','Y','N','N','icon-obrq.png',999,'Y','Y','Y','N','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('RTRQ01M','반품','IW1000M',12100,'MN','/bm/rt2000m/rtrq01m','M','Y','N','Y','icon-return.png',999,'Y','Y','Y','N','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('TRSP01','명세서','OW5000',5080,'MN','/be/ow5000/trsp01','P','N','N','Y',NULL,NULL,'Y','Y','Y','Y','administrator','2026-04-07 10:56:18'::timestamp,'jhkim816','2026-04-09 10:10:56'::timestamp);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('SMBD02','공지사항','SS9300',9370,'MN','/be/ss9300/smbd02','P','N','N','N',NULL,NULL,'Y','Y','N','N','administrator','2026-01-13 17:15:35'::timestamp,'admin','2026-01-13 17:16:10'::timestamp);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IVWH01','재고조회(창고별)','IV3100',3120,'MN','/be/iv3100/ivwh01','P','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IVPR01','재고조회(기간별)','IV3100',3130,'MN','/be/iv3100/ivpr01','P','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IVEXRQ01','예외출고','IV3000',3040,'MN','/be/iv3000/ivexrq01','P','N','N','Y',NULL,0,'Y','Y','Y','N','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('OBED01','출하마감','OW5000',5070,'MN','/be/ow5000/obed01','P','N','N','N',NULL,NULL,'Y','Y','Y','Y','administrator','2026-04-09 10:10:38'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('CM9400','소통관리','ZMROOT',8500,'MG','#','P','N','N','N','icon-mdm.png',0,'Y','Y','Y','N','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('MDSP01','화주','MD8000',8020,'MN','/be/md8000/mdsp01','P','N','N','N',NULL,0,'Y','Y','Y','N','administrator','2025-12-30 10:55:40'::timestamp,'admin','2025-12-30 10:55:55'::timestamp);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('FLSC01M','고정위치조회','IV3100M',13120,'MI','/bm/iv3100m/flsc01m','M','N','N','N','icon-menu-flsc01_nobg.png',75,'Y','Y','Y','Y','administrator','2026-04-01 12:00:56.840613'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('STSC01M','재고실사','IV3200M',13210,'MN','/bm/iv3200m/stsc01m','M','N','N','N','icon-stsc.png',999,'Y','Y','Y','N','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('DLPC01M','송장','OW5000M',15040,'MN','/bm/ow5000m/dlpc01m','M','N','N','Y','icon-owiv.png',999,'Y','Y','Y','N','administrator','2025-08-28 14:23:33.536000'::timestamp,'jhkim816','2026-04-09 11:52:07'::timestamp);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('STDC01','세트해체','IV3000',3090,'MN','/be/iv3000/stdc01','P','N','N','N',NULL,0,'Y','Y','Y','Y','administrator','2026-04-15 11:05:03.045769'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IVMV01M','재고이동','IV3000M',13010,'MN','/bm/iv3000m/ivmv01m','M','N','N','N','icon-ivmv.png',51,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('LDPC01M','검수','OW5000M',15060,'MN','/bm/ow5000m/ldpc01m','M','Y','N','Y','icon-obrq.png',33,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,'jhkim816','2026-04-10 11:03:33'::timestamp);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('RT2000M','[반품관리]','ZMROOT',12000,'MG','#','M','N','N','N',NULL,999,'Y','Y','Y','N','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('IVMVRQ01M','재고이동요청','IV3000M',13020,'MN','/bm/iv3000m/ivmvrq01m','M','Y','N','Y','icon-ivmv-rq.png',53,'Y','Y','Y','Y','administrator','2025-08-28 14:23:33.536000'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('SPMV01M','보충이동확인','IV3000M',13050,'MN','/bm/iv3000m/spmv01m','M','N','N','Y','icon-menu-replenishment_nobg.png',71,'Y','Y','N','Y','jhkim816','2026-02-10 14:42:38'::timestamp,NULL,NULL);
INSERT INTO "public"."sm_menu" ("menu_cd","menu_nm","h_menu_cd","menu_idx","menu_type_cd","menu_url","ui_type_cd","alarm_use_yn","proc_ymd_chng_yn","sch_ymd_set_yn","menu_icon","pda_disp_no","login_acc_yn","login_disp_yn","def_menu_yn","use_yn","reg_id","reg_dt","mod_id","mod_dt") VALUES ('MDPR01','사은품관리','MD8000',8085,'MN','/be/md8000/mdpr01','P','N','N','N',NULL,NULL,'Y','Y','N','Y','administrator','2026-02-05 12:06:13'::timestamp,'jhlee','2026-04-01 10:48:10'::timestamp);

COMMIT;

-- 적용 후 검증
SELECT 'sm_menu' AS tbl, COUNT(*) FROM "public"."sm_menu";
